# System config
permalink: pretty
pygments: true
markdown: rdiscount

# Site config
title: Too Much Recursion
name: Too Much Recursion
url: http://toomuchrecursion.com
theme: default
pagination: 10
excerpt: 50