# System config
permalink: pretty
pygments: true
markdown: rdiscount

# Site config
title: Too Much Recursion
name: Too Much Recursion
shortname: toomuchrecursion
description: 'Brought to you by Dan Drinkard, a hackintosh, and lots of coffee.'
url: http://toomuchrecursion.com
author: Dan Drinkard
author_email: dan.drinkard@gmail.com
theme: default
paginate: 10
excerpt_words: 20